admin/routes.py
'''
   Copyright 2017 Volodymyr Borovkov

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
'''

from flask import Blueprint, render_template, abort, url_for, session, redirect, request, make_response
import os.path
import sys
import json
from passlib.hash import pbkdf2_sha256
from slugify import slugify
from werkzeug.utils import secure_filename
from flask import send_from_directory
from PIL import Image
from collections import OrderedDict

admin_blueprint = Blueprint('admin', __name__,
                            template_folder='templates',
                            static_folder='static')

ALLOWED_EXTENSIONS = set(['txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif'])
IMAGE_EXTENSIONS = set(['png', 'jpg', 'jpeg'])

"""
Dashboard
"""
@admin_blueprint.route('/')
def admin_dash():
    if 'username' in session:
        path = 'content'
        num_files = len([f for f in os.listdir(path)if os.path.isfile(os.path.join(path, f))])
        upath = 'users'
        num_ufiles = len([f for f in os.listdir(upath)if os.path.isfile(os.path.join(upath, f))])
        mpath = 'static/media'
        num_mfiles = len([f for f in os.listdir(mpath)if os.path.isfile(os.path.join(mpath, f))])
        return render_template('admin.html', num_page = num_files, num_users = num_ufiles, num_media = num_mfiles, user = session['username'])
    return redirect(url_for('admin.login'))

"""
Login Form
"""
@admin_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    if 'username' in session:
        return redirect(url_for('admin.admin_dash'))
    if request.method == 'POST':
        if not os.path.isfile("users/%s.json" % request.form['username']):
            error = "Wrong username or password, please try again."
            return render_template("login.html", error=error)
        file = open("users/%s.json" % request.form['username'], "r+")
        json_data = json.loads(file.read())
        password = json_data['password']
        if pbkdf2_sha256.verify(request.form['password'], password):
            session['username'] = request.form['username']
            return redirect(url_for('admin.admin_dash'))
        else:
            error = "Wrong username or password, please try again."
            return render_template("login.html", error=error)
    return render_template("login.html")

@admin_blueprint.route('/logout')
def logout():
    # remove the username from the session if it's there
    session.pop('username', None)
    return redirect(url_for('index'))


"""
Pages
"""
@admin_blueprint.route('/pages')
def admin_pages():
    if 'username' in session:
        path = 'content'
        files = [f for f in os.listdir(path)if os.path.isfile(os.path.join(path, f))]
        return render_template('admin_pages.html', name = files, user = session['username'])
    return redirect(url_for('admin.login'))

@admin_blueprint.route('/newpage', methods=['GET', 'POST'])
def admin_newpage():
    if 'username' in session:
        if request.method == 'POST':
            page_name = request.form['title']
            file = open("content/%s.json" % page_name, "a")
            file.write(json.dumps({"Author": "", "Title": "%s" % page_name, "Content": "", "Date": "", "Slug": ""}))
            return redirect(url_for('admin.admin_pages'))
        return render_template('admin_newpage.html', user = session['username'])
    return redirect(url_for('admin.login'))

@admin_blueprint.route('/pages/<string:page_name>/', methods=['GET', 'POST'])
def admin_pagedetail(page_name):
    if 'username' in session:
        #find theme
        config_file = open("config.json", "r")
        config_data = json.loads(config_file.read())
        THEME = config_data['theme']
        config_file.close()
        #find and open page content
        if not os.path.isfile("content/%s.json" % page_name):
            #TODO Modal error step before
            abort(make_response("<h1 style='color:red;'>Content file for %s page not found!</h1>" % page_name, 404))
        file = open("content/%s.json" % page_name, "r+")
        json_data = json.loads(file.read())
        path = 'themes/%s/Models' % THEME
        template = json_data['Template']
        #find models
        if not os.path.isfile("%s/%s.json" % (path, template)):
            abort(make_response("<h1 style='color:red;'>Model for %s page not found!</h1>" % page_name, 404))
        model = open("%s/%s.json" % (path, template), "r+")
        files = [f for f in os.listdir(path)if os.path.isfile(os.path.join(path, f))]
        json_datastructure = json.loads(model.read(), object_pairs_hook=OrderedDict)
        fields = json_datastructure.items()
        data = json_data.items()
        slug = json_data['Slug']
        model.close()
        file.close()
        if request.method == 'POST':
            for key, value in fields:
                json_data[key] = request.form[key]
            slugpage = slugify(request.form['Title'])
            json_data['Slug'] = slugpage
            json_data['Template'] = request.form['Template']
            os.rename("content/%s.json" % page_name, "content/%s.json" % slugpage)
            file = open("content/%s.json" % slugpage, "w+")
            file.write(json.dumps(json_data))
            return redirect(url_for('admin.admin_pagedetail', page_name = slugpage))
        return render_template('admin_pagedetail.html', page_name = page_name, data = data, slug = slug, fields = fields, files = files, template = template, user = session['username'])
    return redirect(url_for('admin.login'))

@admin_blueprint.route('/pages/delete/<string:page_name>/', methods=['GET', 'POST'])
def admin_pages_delete(page_name):
    if 'username' in session:
        os.remove("content/%s.json" % page_name)
        return redirect(url_for('admin.admin_pages'))
    return redirect(url_for('admin.login'))

"""
Menu
"""
@admin_blueprint.route('/menu', methods=['GET', 'POST'])
def admin_menu():
    if 'username' in session:
        file = open("menu.json", "r")
        json_data = json.loads(file.read())
        title = json_data['menu']
        path = 'content'
        files = [f for f in os.listdir(path)if os.path.isfile(os.path.join(path, f))]
        if request.method == 'POST':
            file = open("menu.json", "w+")
            #test = [x for x in [request.form.getlist['title']]]
            json_data['menu'] = request.form.getlist('title')
            #print test
            file.write(json.dumps(json_data))
            return redirect(url_for('admin.admin_menu'))
        return render_template('admin_menu.html', files = files, name = title, user = session['username'])
    return redirect(url_for('admin.login'))

"""
Media
"""
def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

def image_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in IMAGE_EXTENSIONS

@admin_blueprint.route('/media', methods=['GET', 'POST'])
def admin_media():
    if 'username' in session:
        path = 'static/media'
        files = [f for f in os.listdir(path)if os.path.isfile(os.path.join(path, f))]
        if request.method == 'POST':
            # check if the post request has the file part
            if 'file' not in request.files:
                flash('No file part')
                return redirect(request.url)
            file = request.files['file']
            # if user does not select file, browser also
            # submit a empty part without filename
            if file.filename == '':
                flash('No selected file')
                return redirect(request.url)
            if file and allowed_file(file.filename):
                filename = secure_filename(file.filename)
                file.save(os.path.join("static/media/", filename))
                if image_file(file.filename):
                    thumb = Image.open("static/media/%s" % filename)
                    thumb = thumb.resize((128,128))
                    thumb.save("static/media/thumb/%s" % filename)
                return redirect(url_for('admin.uploaded_file',
                                        filename=filename))
        return render_template('admin_media.html', name = files, user = session['username'])
    return redirect(url_for('admin.login'))

@admin_blueprint.route('/uploads/<filename>')
def uploaded_file(filename):
    if 'username' in session:
        name = "../../static/media/%s" % filename
        return render_template('admin_mediadetail.html',  name = name, user = session['username'])
    return redirect(url_for('admin.login'))

@admin_blueprint.route('/media/delete/<string:media_name>/', methods=['GET', 'POST'])
def admin_media_delete(media_name):
    if 'username' in session:
        os.remove("static/media/%s" % media_name)
        if os.path.isfile("static/media/thumb/%s" % media_name):
            os.remove("static/media/thumb/%s" % media_name)
        return redirect(url_for('admin.admin_media'))
    return redirect(url_for('admin.login'))

"""
Templates
"""
@admin_blueprint.route('/templates')
def admin_templates():
    if 'username' in session:
        config_file = open("config.json", "r")
        config_data = json.loads(config_file.read())
        THEME = config_data['theme']
        config_file.close()
        path = 'themes/%s/Templates' % THEME
        files = [f for f in os.listdir(path)if os.path.isfile(os.path.join(path, f))]

admin/templates/admin.html
{% extends "admin_layout.html" %}

{% block body %}

  <!-- Header -->
  <header class="w3-container w3-card-4" style="padding-top:22px">
    <h3><i class="mbri-desktop"></i><b> My Dashboard</b></h3>
  </header>
  <br>

  <div class="w3-row-padding w3-margin-bottom">
    <div class="w3-quarter">
      <a href="{{ url_for('admin.admin_pages') }}">
      <div class="w3-container w3-red w3-hover-opacity w3-padding-16 tile">
        <div class="w3-left"><i class="mbri-file" style="font-size:90px"></i></div>
        <div class="w3-right">
          <h3>{{num_page}}</h3>
        </div>
        <div class="w3-clear"></div>
        <h3>Pages</h3>
      </div>
    </a>
    </div>
    <div class="w3-quarter">
      <a href="{{ url_for('admin.admin_users') }}">
        <div class="w3-container w3-blue w3-hover-opacity w3-padding-16 tile">
          <div class="w3-left"><i class="mbri-users" style="font-size:90px"></i></div>
          <div class="w3-right">
            <h3>{{num_users}}</h3>
          </div>
          <div class="w3-clear"></div>
          <h3>Users</h3>
        </div>
      </a>
    </div>
    <div class="w3-quarter">
      <a href="{{ url_for('admin.admin_media') }}">
        <div class="w3-container w3-teal w3-hover-opacity w3-padding-16 tile">
          <div class="w3-left"><i class="mbri-photos" style="font-size:90px"></i></div>
          <div class="w3-right">
            <h3>{{num_media}}</h3>
          </div>
          <div class="w3-clear"></div>
          <h3>Media-Files</h3>
        </div>
      </a>
    </div>
    <div class="w3-quarter">
      <div class="w3-container w3-orange w3-hover-opacity w3-text-white w3-padding-16 tile">
        <div class="w3-left"><i class="mbri-website-theme" style="font-size:90px"></i></div>
        <div class="w3-right">
          <h3>2</h3>
        </div>
        <div class="w3-clear"></div>
        <h3>Themes</h3>
      </div>
    </div>
  </div>

  <div class="w3-container w3-center">
    <h1>Welcome, {{user}}</h1>
  </div>

  <div class="w3-container">
    <h5>Recent News</h5>

    <div class="w3-row">
      <div class="w3-col m2 text-center">
        <img class="w3-circle" src="{{ url_for('admin.static', filename='images/avatar2.png') }}" style="width:96px;height:96px">
      </div>
      <div class="w3-col m10 w3-container">
        <h4>Admin <span class="w3-opacity w3-medium">1st of May, 2017, 14:22</span></h4>
        <p>HelloCMS is now v0.4.5! Data models added.</p>
      </div>
    </div>
    <br>
    <div class="w3-row">
      <div class="w3-col m2 text-center">
        <img class="w3-circle" src="{{ url_for('admin.static', filename='images/avatar2.png') }}" style="width:96px;height:96px">
      </div>
      <div class="w3-col m10 w3-container">
        <h4>Admin <span class="w3-opacity w3-medium">23rd of April, 2017, 13:21</span></h4>
        <p>HelloCMS is now v0.4.1! You can now edit templates.</p>
      </div>
    </div>
  </div>
  <br>

  <!-- Footer -->
  <footer class="w3-container w3-padding-16 w3-light-grey">
    <p></p>
  </footer>
{% endblock %}

admin/templates/admin_layout.html
<!DOCTYPE html>
<html>
<title>Dashboard</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel=stylesheet type=text/css href="{{ url_for('admin.static', filename='css/w3.css') }}">
<link rel=stylesheet type=text/css href="{{ url_for('admin.static', filename='css/main.css') }}">
<link rel=stylesheet type=text/css href="{{ url_for('admin.static', filename='css/jquery-ui.min.css') }}">
<link rel="stylesheet" type=text/css href="{{ url_for('admin.static', filename='css/style.css') }}">
<link rel="stylesheet" type=text/css href="{{ url_for('admin.static', filename='js/Trumbowyg/dist/ui/trumbowyg.min.css') }}">
<script src="{{ url_for('admin.static', filename='js/jquery-3.1.1.min.js') }}"></script>
<body class="w3-light-grey">


<!-- Sidenav/menu -->
<nav class="w3-sidenav w3-collapse w3-text-white" style="background-color:#212121; z-index:3;width:250px;font-size:16px;top:0;" id="mySidenav"><br>
  <div class="w3-container w3-center">
    <img src="{{ url_for('admin.static', filename='images/logo.png') }}" height="36px">
  </div>
  <hr>
  <a href="{{ url_for('admin.admin_dash') }}" class="w3-padding {% if request.path == '/admin/' %}w3-blue{% endif %}"><i class="mbri-desktop"></i>  Dashboard</a>
  <a href="{{ url_for('admin.admin_pages') }}" class="w3-padding {% if request.path == '/admin/pages' %}w3-blue{% endif %}"><i class="mbri-file"></i>  Pages</a>
  <a href="{{ url_for('admin.admin_menu') }}" class="w3-padding {% if request.path == '/admin/menu' %}w3-blue{% endif %}"><i class="mbri-sites"></i>  Menu</a>
  <a href="{{ url_for('admin.admin_media') }}" class="w3-padding {% if request.path == '/admin/media' %}w3-blue{% endif %}"><i class="mbri-photos"></i>  Media</a>
  <a href="{{ url_for('admin.admin_templates') }}" class="w3-padding {% if request.path == '/admin/templates' %}w3-blue{% endif %}"><i class="mbri-website-theme"></i>  Templates</a>
  <!--<a href="#"><i class="mbri-extension"></i>  Widgets</a>-->
  <a href="{{ url_for('admin.admin_users') }}" class="w3-padding {% if request.path == '/admin/users' %}w3-blue{% endif %}"><i class="mbri-users"></i>  Users</a>
  <a href="{{ url_for('admin.admin_settings') }}" class="w3-padding"><i class="mbri-setting3"></i>  Settings</a>
  <hr>
  <a href="{{ url_for('admin.logout') }}"><i class="mbri-logout"></i>&nbsp;Logout</a>
  <a href="#" class="w3-padding-16 w3-hide-large w3-closenav w3-dark-grey w3-hover-black" onclick="w3_close()" title="close menu"><i class="mbri-close"></i>  Close Menu</a>
</nav>


<!-- Overlay effect when opening sidenav on small screens -->
<div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:250px;margin-top:0;">

  {% block body %}{% endblock %}

  <!-- End page content -->
</div>
<script src="{{ url_for('admin.static', filename='js/jquery-ui.min.js') }}"></script>
<script src="{{ url_for('admin.static', filename='js/ace.js') }}"></script>
<script src="{{ url_for('admin.static', filename='js/functions.js') }}"></script>
<script>window.jQuery || document.write('<script src="{{ url_for("admin.static", filename="js/jquery-3.1.1.min.js") }}"><\/script>')</script>
<script src="{{ url_for('admin.static', filename='js/Trumbowyg/dist/trumbowyg.min.js') }}"></script>

</body>
</html>

admin/templates/admin_media.html
{% extends "admin_layout.html" %}

{% block body %}

  <!-- Header -->
  <header class="w3-container w3-card-4" style="padding-top:22px">
    <div class="w3-row">
      <div class="w3-half">
        <h3><i class="mbri-file"></i><b> Media</b></h3>
      </div>
      <div class="w3-half">
        <form method="post" enctype="multipart/form-data">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
          <input type="file" class="w3-btn w3-card-4 w3-round w3-white w3-blue w3-hover-light-blue" name="file">
          <input type="submit" class="w3-btn w3-card-4 w3-round w3-white w3-blue w3-hover-light-blue" value="Upload">
        </form>
      </div>
    </div>
  </header>

  <div class="w3-container">
    <h5>All Media Files</h5>
    <ul class="w3-ul">
      {% for title in name %}
      <li>

        <a href="{{ url_for('admin.uploaded_file', filename=title)}}">
          <div class="w3-col w3-card-4 w3-padding w3-white w3-hover-blue" style="width:90%">
            <img src="{{ url_for('admin.static', filename='../../static/media/thumb/%s' % title) }}" width="50px">
            <span class="w3-xlarge" style="top: -10px;position: relative;">{{title}}</span>
          </div>
        </a>
        <a href="{{ url_for('admin.admin_media_delete', media_name=title ) }}">
          <div class="w3-col w3-padding" style="width:10%">
            <i class="w3-xlarge w3-text-red w3-text-hover-orange mbri-trash" style="top: 15px;position: relative;"></i>
          </div>
        </a>
      </li>
      {% endfor %}
    </ul>
  </div>

{% endblock %}

admin/templates/admin_mediadetail.html
{% extends "admin_layout.html" %}

{% block body %}

  <!-- Header -->
  <header class="w3-container w3-card-4" style="padding-top:22px">
    <div class="w3-row">
      <div class="w3-half">
        <h3><i class="mbri-file"></i><b> Media</b></h3>
      </div>
      <div class="w3-half">
          <a href="{{ url_for('admin.admin_media') }}" class="w3-btn w3-card-4 w3-round w3-red w3-right w3-hover-deep-orange" ><span class="mbri-arrow-prev"></span> Back</a>
      </div>
    </div>
  </header>

  <div class="w3-container">
    <h5>Uploaded file</h5>
    <img src="{{name}}">
  </div>

{% endblock %}

admin/templates/admin_menu.html
{% extends "admin_layout.html" %}

{% block body %}

  <!-- Header -->
  <form method="POST">
  <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
  <header class="w3-container w3-card-4" style="padding-top:22px">
    <div class="w3-row">
      <div class="w3-threequarter">
        <h3><i class="mbri-file"></i> <b>Menu</b></h3>
      </div>
      <div class="w3-quarter">
        <input type="submit" class="w3-btn w3-green w3-card-4 w3-round w3-save w3-hover-light-green" value="&#xe959; Save"  style="font-weight:600;font-family:'MobiriseIcons' !important;">
      </div>
    </div>
  </header>

  <div class="w3-twothird w3-padding">
  <h5>Menu:</h5>
  <ul class="w3-ul connectedSortable" id="sortable1" style="border: 3px dashed black; height:500px">
  {% for title in name %}
  <li id="{{title}}">
    <div class="w3-col w3-card-4 w3-padding w3-white w3-hover-blue">
        <span class="w3-xlarge">{{title|replace(".json", "")}}</span>
        <input type="hidden" name="title" value="{{ title|replace(".json", "") }}"/>
        <span onclick="this.parentNode.parentNode.parentNode.removeChild(this.parentNode.parentNode)" class="w3-closebtn w3-padding w3-margin-right w3-medium">x</span>
    </div>
  </li>
  {% endfor %}
  </ul>
  </div>
  </form>


    <div class="w3-third w3-padding">
      <h5>Avaible Pages:</h5>
      <ul class="w3-ul connectedSortable" id="sortable2">
        {% for title in files %}
        <li id="{{title}}">
          <div class="w3-col w3-card-4 w3-padding w3-white w3-hover-blue">
              <span class="w3-xlarge">{{title|replace(".json", "")}}</span>
              <input type="hidden" name="title" value="{{ title|replace(".json", "") }}"/>
              <span onclick="this.parentNode.parentNode.parentNode.removeChild(this.parentNode.parentNode)" class="w3-closebtn w3-padding w3-margin-right w3-medium">x</span>
            </div>
        </li>
        {% endfor %}
      </ul>
    </div>

{% endblock %}

admin/templates/admin_pages.html
{% extends "admin_layout.html" %}

{% block body %}

  <!-- Header -->
  <header class="w3-container w3-card-4" style="padding-top:22px">
    <div class="w3-row">
      <div class="w3-threequarter">
        <h3><i class="mbri-file"></i><b> Pages</b></h3>
      </div>
      <div class="w3-quarter">
          <a href="{{ url_for('admin.admin_newpage') }}" type="submit" class="w3-btn w3-card-4 w3-round w3-blue w3-hover-light-blue w3-right"> <span class="mbri-plus"></span> New Page</a>
      </div>
    </div>
  </header>

  <div class="w3-container">
    <h5>All Pages</h5>
    <ul class="w3-ul">
      {% for title in name %}
      <li>
        <a href="{{ url_for('admin.admin_pagedetail', page_name=title|replace('.json', '') ) }}">
          <div class="w3-col w3-card-4 w3-padding w3-white w3-hover-blue" style="width:90%">
            <span class="w3-xlarge">{{title|replace(".json", "")}}</span>
            <span class="w3-xlarge">{{date}}</span><br>
          </div>
        </a>
        <a href="{{ url_for('admin.admin_pages_delete', page_name=title|replace('.json', '') ) }}">
          <div class="w3-col w3-padding" style="width:10%">
            <i class="w3-xlarge w3-text-red w3-text-hover-orange mbri-trash"></i>
          </div>
        </a>
      </li>
      {% endfor %}
    </ul>
  </div>


{% endblock %}

admin/templates/admin_templatedetail.html
{% extends "admin_layout.html" %}

{% block body %}

  <!-- Header -->
  <form method="POST" style="margin-top:-2px;">
  <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
  <header class="w3-container w3-card-4" style="padding-top:22px">
    <div class="w3-row">
      <div class="w3-threequarter">
        <h3><i class="mbri-file"></i><b> {{title}}</b></h3>
      </div>
      <div class="w3-quarter">
          <div class="w3-half w3-padding">
            <input type="submit" class="w3-btn w3-card-4 w3-round w3-block w3-save w3-hover-light-green" value="&#xe959; Save"  style="font-weight:600;font-family:'MobiriseIcons' !important;">
          </div>
          <div class="w3-half w3-padding">
            <a href="{{ url_for('admin.admin_templates') }}" class="w3-btn w3-block w3-card-4 w3-round w3-red w3-hover-deep-orange" ><span class="mbri-arrow-prev"></span> Back</a>
          </div>
      </div>
   </div>
  </header>

  <div class="w3-container">
    <div class="w3-row">
        <h5>Title</h5>
        <input class="w3-input" type="text" name="title" value="{{title}}">
    </div>
    <h5>Code</h5>
    <div style="position:relative;height:500px;">
      <div id="editor">{{code}}</div>
      <textarea id="area" name="code" style="display: none;">{{code}}</textarea>
    </div>
  </div>
  </form>

{% endblock %}

admin/templates/admin_templates.html
{% extends "admin_layout.html" %}

{% block body %}

  <!-- Header -->
  <header class="w3-container w3-card-4" style="padding-top:22px">
    <div class="w3-row">
      <div class="w3-threequarter">
        <h3><i class="mbri-file"></i><b> Templates</b></h3>
      </div>
      <div class="w3-quarter">
          <a href="{{ url_for('admin.admin_newpage') }}" type="submit" class="w3-btn w3-card-4 w3-white w3-border w3-border-blue w3-text-blue w3-hover-blue w3-round w3-right"> <span class="mbri-plus"></span> New Page</a>
      </div>
    </div>
  </header>

  <div class="w3-container">
    <h5>All Templates</h5>
    <ul class="w3-ul">
      {% for title in name %}
      <li>
        <a href="{{ url_for('admin.admin_templatedetail', template_name=title|replace('.html', '') ) }}">
          <div class="w3-col w3-card-4 w3-padding w3-white w3-hover-blue" style="width:90%">
            <span class="w3-xlarge">{{title|replace(".html", "")}}</span>
          </div>
        </a>
        <a href="{{ url_for('admin.admin_pages_delete', page_name=title|replace('.json', '') ) }}">
          <div class="w3-col w3-padding" style="width:10%">
            <i class="w3-xlarge w3-text-red w3-text-hover-orange mbri-trash"></i>
          </div>
        </a>
      </li>
      {% endfor %}
    </ul>
  </div>


{% endblock %}

admin/templates/admin_userdetail.html
{% extends "admin_layout.html" %}

{% block body %}

  <!-- Header -->
  <form method="POST">
  <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
  <header class="w3-container w3-card-4" style="padding-top:22px">
    <div class="w3-row">
      <div class="w3-threequarter">
        <h3><i class="mbri-file"></i><b> {{username}}</b></h3>
      </div>
      <div class="w3-quarter">
        <input type="submit" class="w3-btn w3-card-4 w3-round w3-save w3-hover-light-green" value="&#xe959; Save"  style="font-weight:600;font-family:'MobiriseIcons' !important;">
        <a href="{{ url_for('admin.admin_users') }}" class="w3-btn w3-card-4 w3-round w3-red w3-hover-deep-orange" style="font-weight:600;font-family:'MobiriseIcons' !important;">&#xe904 Back</a>
      </div>
   </div>
  </header>

  <div class="w3-container">
    <h5>User Name</h5>
    <input class="w3-input" type="text" name="username" value="{{username}}">
  </div>
  </form>

{% endblock %}

admin/templates/admin_widgets.html
{% extends "admin_layout.html" %}

{% block body %}

  <!-- Header -->
  <header class="w3-container w3-card-4" style="padding-top:22px">
    <div class="w3-row">
      <div class="w3-threequarter">
        <h3><i class="mbri-file"></i><b> Widgets</b></h3>
      </div>
      <div class="w3-quarter">
          <a href="{{ url_for('admin.admin_newpage') }}" type="submit" class="w3-btn w3-card-4 w3-round w3-blue w3-hover-light-blue w3-right"> <span class="mbri-plus"></span> New Page</a>
      </div>
    </div>
  </header>

  <div class="w3-container">
    <h5>All Widgets</h5>
    <ul class="w3-ul">
      {% for title in name %}
      <li>
        <a href="{{ url_for('admin.admin_widgetdetail', widget_name=title|replace('.json', '') ) }}">
          <div class="w3-col w3-card-4 w3-padding w3-white w3-hover-blue" style="width:90%">
            <span class="w3-xlarge">{{title|replace(".json", "")}}</span>
          </div>
        </a>
        <a href="{{ url_for('admin.admin_pages_delete', page_name=title|replace('.json', '') ) }}">
          <div class="w3-col w3-padding" style="width:10%">
            <i class="w3-xlarge w3-text-red w3-text-hover-orange mbri-trash"></i>
          </div>
        </a>
      </li>
      {% endfor %}
    </ul>
  </div>


{% endblock %}